  json.id cable.id
  json.name cable.name
  json.price cable.price
  json.length cable.length
  json.function cable.function
  json.model_year cable.model_year
  json.description cable.description
  json.in_stock? cable.in_stock
  json.discount cable.is_discounted?
  json.tax cable.tax
  json.total cable.total
  json.vendor cable.vendor_id